clone_folder: C:\msys64\home\installer
image: Visual Studio 2019

environment:
  PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Git\cmd;C:\Program Files\7-Zip
  RTOOLS_ARCH: x86_64
  INSTALLER: rtools64.iss

  PfxUri:
    secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22ewYZAm6XZ8jsdphTFYkn7L
  CertPassword:
    secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
  SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
  KeyFile: C:\jeroen.pfx

install:
    - ps: Import-Module .\scripts.ps1
    - ps: UpdateMSYS2
    - ps: InstallInno

build_script:
  - xcopy /y pacman-bootstrap.conf C:\msys64\etc\pacman.conf
  - C:\msys64\usr\bin\pacman --noconfirm -Syyu
  - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/make-rtools-chroot.sh"
  - ps: InnoBuild
  - 7z a rtools40-%RTOOLS_ARCH%.7z .\build\rtools40\

after_build:
  - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
  - ps: SignFiles "Output\*.exe"
  - ps: Remove-Item –path $env:KeyFile

test: off

artifacts:
  - path: rtools*.7z
  - path: Output\*.exe
